const user = [
  {
    id: 1,
    Name: "bukky",
    age: 3.5,
    email: "bukky@home.com",
    image: "/bukky.jpg",
    phone: "098-9895888",
    role: "Sr.develop",
    password: "securepassword123",
  },
  {
    id: 2,
    Name: "deisy",
    age: 1.2,
    email: "deisy@home.com",
    image: "/S__7667726_0.jpg",
    phone: "098-9895888",
    role: "Lead",
    password: "securepassword123",
  },
  {
    id: 3,
    Name: "Robinhood",
    age: 30,
    email: "Robinhood@Robinhood.com",
    image: "/nut.jpg",
    phone: "5",
    role: "HR",
    password: "mypassword456",
  },
  {
    id: 4,
    Name: "Jon Snow",
    age: 40,
    email: "Jon_Snow@filllikecool.com",
    image: "/Jon_Snow.png",
    phone: "088-8885648",
    role: "admin",
    password: "mypassword456",
  },
  {
    id: 6,
    Name: "Nutthawat",
    age: 28,
    email: "Nutthawat@gmail.com",
    image: "/20191216_082746.jpg",
    phone: "098-2691859",
    role: "user",
    password: "mypassword456",
  },
  {
    id: 5,
    Name: "Titan",
    age: 40,
    email: "Titan@gmail.com",
    image: "/Titan.jpg",
    phone: "026-755888",
    role: "Manager",
    password: "securepassword123",
  },
];
module.exports = user;
